# Generated by Django 5.1 on 2024-09-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="household",
            name="description",
        ),
        migrations.AlterField(
            model_name="household",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
