# Generated by Django 5.1.1 on 2024-09-29 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_remove_household_description_alter_household_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="merchant",
            field=models.ForeignKey(
                default="73083bbf-af85-4e75-947e-d67fb3c67d8a",
                on_delete=django.db.models.deletion.CASCADE,
                to="api.merchant",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="expense",
            name="payment_type",
            field=models.ForeignKey(
                default="04caa5f0-ebe4-4074-9367-8188bcfb1d0c",
                on_delete=django.db.models.deletion.CASCADE,
                to="api.paymenttype",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.ForeignKey(
                default="a8062262-e83e-428b-81d0-b72c03c7ea90",
                on_delete=django.db.models.deletion.CASCADE,
                to="api.category",
            ),
            preserve_default=False,
        ),
    ]
