# Generated by Django 5.1.1 on 2024-09-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_expense_merchant_expense_payment_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="title",
            field=models.CharField(default="Test expense", max_length=255),
            preserve_default=False,
        ),
    ]
