# Generated by Django 5.1 on 2024-09-03 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_category_merchant_paymenttype_expense_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="household",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.household",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="merchant",
            name="household",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.household",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paymenttype",
            name="household",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.household",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="expense",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
