# Generated by Django 5.1 on 2024-09-27 16:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_category_household_merchant_household_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
