# Generated by Django 5.1.1 on 2024-09-29 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="location",
            field=models.CharField(default="Toulouse", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paymenttype",
            name="user",
            field=models.ForeignKey(
                default="975a6142-20cd-4fd7-ad40-8c49497ff966",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="expense",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
