# Generated by Django 5.1.1 on 2024-09-29 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_expense_location_paymenttype_user_alter_expense_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="user",
            field=models.ForeignKey(
                default="975a6142-20cd-4fd7-ad40-8c49497ff966",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="household",
            name="user",
            field=models.ForeignKey(
                default="975a6142-20cd-4fd7-ad40-8c49497ff966",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="merchant",
            name="user",
            field=models.ForeignKey(
                default="975a6142-20cd-4fd7-ad40-8c49497ff966",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
