# Generated by Django 5.1.1 on 2024-09-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_category_user_household_user_merchant_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="is_active_subscription",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="expense",
            name="is_subscription",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="expense",
            name="recurrence_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="expense",
            name="recurrence_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="expense",
            name="recurrence_type",
            field=models.IntegerField(
                choices=[
                    (1, "Daily"),
                    (7, "Weekly"),
                    (30, "Monthly"),
                    (90, "Quarterly"),
                    (180, "Semester"),
                    (365, "Yearly"),
                ],
                default=30,
            ),
        ),
    ]
