# Generated by Django 5.1.1 on 2024-09-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_expense_is_active_subscription_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="colour_hex",
            field=models.CharField(default="0", max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.CharField(default="a", max_length=100),
            preserve_default=False,
        ),
    ]
