# Generated by Django 5.1.1 on 2024-09-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_category_colour_hex_category_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="monthly_budget",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="colour_hex",
            field=models.CharField(default="0", max_length=9),
            preserve_default=False,
        ),
    ]
